// src/core/errors/codes.ts
export enum ErrorCode {
  // Core Config Errors
  CONFIG_INVALID          = 'CONFIG_INVALID',
  INVALID_CONFIGURATION   = 'INVALID_CONFIGURATION',
  TEMPLATE_DUPLICATE      = 'TEMPLATE_DUPLICATE',
  TEMPLATE_NOT_FOUND      = 'TEMPLATE_NOT_FOUND',
  
  // File System Errors
  FS_READ                 = 'FS_READ',
  FS_WRITE                = 'FS_WRITE',
  FS_DELETE               = 'FS_DELETE',
  
  // Server Lifecycle Errors
  SERVER_STARTUP_ERROR    = 'SERVER_STARTUP_ERROR',
  SERVER_SHUTDOWN_ERROR   = 'SERVER_SHUTDOWN_ERROR',
  SERVER_STOP_ERROR       = 'SERVER_STOP_ERROR',
  SERVER_RESTART_ERROR    = 'SERVER_RESTART_ERROR',
  SERVER_DELETE_ERROR     = 'SERVER_DELETE_ERROR',
  SERVER_ALREADY_RUNNING  = 'SERVER_ALREADY_RUNNING',
  SERVER_NOT_FOUND        = 'SERVER_NOT_FOUND',
  
  // Deployment Errors
  DEPLOY_ERROR            = 'DEPLOY_ERROR',
  UNDEPLOY_ERROR          = 'UNDEPLOY_ERROR',
  DEPLOYMENT_UPDATE_ERROR = 'DEPLOYMENT_UPDATE_ERROR',
  DEPLOYMENT_NOT_FOUND    = 'DEPLOYMENT_NOT_FOUND',
  PORT_UNAVAILABLE        = 'PORT_UNAVAILABLE',
  AUTOSYNC_TOGGLE_ERROR   = 'AUTOSYNC_TOGGLE_ERROR',
  
  // Plugin System Errors
  PLUGIN_ERROR            = 'PLUGIN_ERROR',
  PLUGIN_NOT_FOUND        = 'PLUGIN_NOT_FOUND',
  PLUGIN_REGISTRATION_ERROR = 'PLUGIN_REGISTRATION_ERROR',
  PLUGIN_CREATION_ERROR   = 'PLUGIN_CREATION_ERROR',
  PLUGIN_VALIDATION_ERROR = 'PLUGIN_VALIDATION_ERROR',
  PLUGIN_RELOAD_ERROR     = 'PLUGIN_RELOAD_ERROR',
  
  // Runtime Errors
  RUNTIME_CREATION_ERROR  = 'RUNTIME_CREATION_ERROR',
  RUNTIME_REGISTRATION_ERROR = 'RUNTIME_REGISTRATION_ERROR',
  RUNTIME_UNREGISTRATION_ERROR = 'RUNTIME_UNREGISTRATION_ERROR',
  
  // Cache Errors
  CACHE_ERROR             = 'CACHE_ERROR',
  
  // Command & Operation Errors
  COMMAND_EXECUTION_ERROR = 'COMMAND_EXECUTION_ERROR',
  COMMAND_BUILD_ERROR     = 'COMMAND_BUILD_ERROR',
  
  // Status & Monitoring Errors
  STATUS_MONITOR_ERROR    = 'STATUS_MONITOR_ERROR',
  STATUS_CHECK_ERROR      = 'STATUS_CHECK_ERROR',
  HEALTH_CHECK_ERROR      = 'HEALTH_CHECK_ERROR',
  
  // Server Detection & Installation
  SERVER_TYPE_DETECTION_ERROR = 'SERVER_TYPE_DETECTION_ERROR',
  INSTALLATION_VALIDATION_ERROR = 'INSTALLATION_VALIDATION_ERROR',
  
  // Instance Management
  INSTANCE_CREATION_ERROR = 'INSTANCE_CREATION_ERROR',
  INSTANCE_NOT_FOUND      = 'INSTANCE_NOT_FOUND',
  INSTANCE_REMOVAL_ERROR  = 'INSTANCE_REMOVAL_ERROR',
  INSTANCE_VALIDATION_ERROR = 'INSTANCE_VALIDATION_ERROR',
  
  // Template Management
  TEMPLATE_REGISTRATION_ERROR = 'TEMPLATE_REGISTRATION_ERROR',
  TEMPLATE_DELETION_ERROR = 'TEMPLATE_DELETION_ERROR',
  
  // System Errors
  TIMEOUT_ERROR           = 'TIMEOUT_ERROR',
  LOG_READ_ERROR          = 'LOG_READ_ERROR',
  METRICS_ERROR           = 'METRICS_ERROR',
  BULK_OPERATION_ERROR    = 'BULK_OPERATION_ERROR',
  
  // Configuration System Errors
  CONFIG_INITIALIZATION_FAILED = 'CONFIG_INITIALIZATION_FAILED',
  CONFIG_MIGRATION_FAILED = 'CONFIG_MIGRATION_FAILED',
  CONFIG_VALIDATION_FAILED = 'CONFIG_VALIDATION_FAILED',
  
  // Fallback
  UNKNOWN                 = 'UNKNOWN'
}