// src/core/errors/codes.ts
export enum ErrorCode {
  CONFIG_INVALID          = 'CONFIG_INVALID',
  TEMPLATE_DUPLICATE      = 'TEMPLATE_DUPLICATE',
  TEMPLATE_NOT_FOUND      = 'TEMPLATE_NOT_FOUND',
  FS_READ                 = 'FS_READ',
  FS_WRITE                = 'FS_WRITE',
  FS_DELETE               = 'FS_DELETE',
  SERVER_STARTUP_ERROR    = 'SERVER_STARTUP_ERROR',
  SERVER_SHUTDOWN_ERROR   = 'SERVER_SHUTDOWN_ERROR',
  SERVER_NOT_FOUND        = 'SERVER_NOT_FOUND',
  DEPLOY_ERROR            = 'DEPLOY_ERROR',
  UNDEPLOY_ERROR          = 'UNDEPLOY_ERROR',
  PORT_UNAVAILABLE        = 'PORT_UNAVAILABLE',
  AUTOSYNC_TOGGLE_ERROR   = 'AUTOSYNC_TOGGLE_ERROR',
  UNKNOWN                 = 'UNKNOWN'
}